steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'vuhoangnamdoan/cloud-task-backend:latest', './backend']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'vuhoangnamdoan/cloud-task-frontend:latest', './frontend']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'vuhoangnamdoan/cloud-task-backend:latest']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'vuhoangnamdoan/cloud-task-frontend:latest']

images:
  - 'vuhoangnamdoan/cloud-task-backend:latest'
  - 'vuhoangnamdoan/cloud-task-frontend:latest'
